### ISSUE TITLE
Clutter

### ISSUE THREAD

**Issue by eliasmalik** [fourloops/StopwatchSamTom#11]
Seems like theres a lot of duplicate html. Why do you need a file call "backup" when you're using version control?

**Comment by eliasmalik** [comment]
Also some dodgy filenames: "nscript.js", "original.js",

**Comment by tu6619** [comment]
@em-12 our clutter file is strictly for our own reference and provides valuable insight into the origins of fumbling blindly through the world of js, html and css, we like to keep a record of our earlier failings, we hope you understand, please feel free to add any additional comments

**Comment by eliasmalik** [comment]
@tu6619 fair enough, although consider keeping that stuff in a branch. Having random files that don't actually do anything on the master branch can confuse people when viewing/using your repo.

I'm closing the issue anyway though.
