### ISSUE TITLE
Folder structure confusing

### ISSUE THREAD

**Issue by franzmoro** [fourloops/StopwatchSamTom#12]
index.html - file should be available in root
I also don't understand why there are this many html files. Maybe just get rid of the whole stopwatch clutter.

PS. Sorry to take it out on my own team-mates! ;)
I really liked the design, awesome as usual!

**Comment by tu6619** [comment]
index.html file renamed, clutter kept for educational/learning purposes (we want to have a record of our progress and why/what/how we changed various aspects of the code) - we hope you understand, don't worry we won't clutter anything in future collaborative projects.

p.s. when are we coming round to yours for pasta?

**Comment by franzmoro** [comment]
@tu6619 soon! :spaghetti: :spaghetti: :spaghetti: :spaghetti:  @oturnermajor @shouston3
